"use client";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import localFont from "next/font/local";
import { useRef } from "react";
const myFont = localFont({
  src: "./font/IRANSans.ttf",
  display: "swap",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
      </head>
      <body className={myFont.className}>
        <section className="bg-[rgb(245,245,245)]">
          <Nav />
          {children}
          <Footer />
        </section>
      </body>
    </html>
  );
}

function Nav() {
  const xx = useRef();
  function menu() {
    xx.current.style.display = "flex";
  }
  function _close() {
    xx.current.style.display = "none";
  }
  return (
    <>
      <nav className="w-[100%] h-[10vh]  flex">
        <section className="w-[50%] h-[100%] flex">
          <ul className="w-[100%] h-[100%] flex gap-10 justify-center items-center">
            <li onClick={menu} className="flex lg:hidden relative">
              <i className="bi bi-list text-[3rem] cursor-pointer"></i>
            </li>
            <li>
              <Link href="/">
                <Image
                  src="/img1.png"
                  alt="Picture of the author"
                  width={1000}
                  height={1000}
                  style={{
                    width: "4rem",
                    height: "3rem",
                    objectFit: "cover",
                  }}
                />
              </Link>
            </li>
            <li className="hidden lg:flex">
              <Link href="">پنل مدیریت</Link>
            </li>
            <li className="hidden lg:flex">
              <Link href="./BuyingRules">قوانین خرید</Link>
            </li>
            <li className="hidden lg:flex">
              <Link href="./ContactUs">تماس با ما</Link>
            </li>
            <li className="hidden lg:flex">
              <Link href="./ss">پرسش های متداول</Link>
            </li>
          </ul>
        </section>
        <section className="w-[50%] h-[100%] flex items-center justify-end px-2 lg:px-16">
          <ul className="w-[100%] lg:w-[20%] h-[60%]">
            <li className="group w-[100%] h-[100%] flex justify-around items-center relative border text-[1rem] rounded-lg cursor-pointer bg1 text-white">
              <i className="bi bi-person-fill text-[1.2rem]"></i>
              پنل کاربری
              <i className="bi bi-chevron-down text-[.7rem]"></i>
              <ul className="text-black rounded-lg *:w-[100%] *:h-[5vh] *:flex *:items-center *:p-5 p-2 hidden group-hover:block transition-all duration-300 w-[150%] absolute top-[100%] left-0 bg-white z-50">
                <li className="hover:bg-zinc-200 transition-all duration-300 rounded-lg">
                  <Link href="./mmmm">خرید های من</Link>
                </li>
                <li className="hover:bg-zinc-200 transition-all duration-300 rounded-lg">
                  <Link href="./trkonsh">تراکنش ها</Link>
                </li>
                <li className="hover:bg-zinc-200 transition-all duration-300 rounded-lg">
                  <Link href="./chat">تیکت (پشتیبانی)</Link>
                </li>
                <li className="hover:bg-zinc-200 transition-all duration-300 rounded-lg">
                  <Link href="./profile">ویراش پروفایل</Link>
                </li>
                {/* <li className="hover:bg-zinc-200 transition-all duration-300 rounded-lg">
                  <Link href="">خروج</Link>
                </li> */}
              </ul>
            </li>
          </ul>
        </section>
      </nav>
      <div
        ref={xx}
        style={{ display: "none" }}
        className="w-[100%] h-[100vh] bg-[rgba(0,0,0,.7)] flex lg:hidden justify-center items-center fixed top-0 z-50"
      >
        <ul className="w-[90%] rounded-lg text-[2rem] h-[80vh] bg-white flex-wrap *:w-[100%] *:flex *:justify-center *:items-center *:h-[20%] gap-10 justify-center items-center">
          <li>
            <i
              onClick={_close}
              className="bi bi-x-square-fill text-[2.5rem] cursor-pointer text-zinc-500 hover:text-red-600 transition-all duration-300"
            ></i>
          </li>
          <li className="hover:bg-zinc-400 transition-all duration-300">
            <Link href="">پنل مدیریت</Link>
          </li>
          <li className="hover:bg-zinc-400 transition-all duration-300">
            <Link href="./BuyingRules">قوانین خرید</Link>
          </li>
          <li className="hover:bg-zinc-400 transition-all duration-300">
            <Link href="./ContactUs">تماس با ما</Link>
          </li>
          <li className="hover:bg-zinc-400 transition-all duration-300">
            <Link href="./ss">پرسش های متداول</Link>
          </li>
        </ul>
      </div>
    </>
  );
}

function Footer() {
  return (
    <footer className="w-[100%] h-[16vh] lg:h-[8vh] bg-zinc-300 flex flex-wrap">
      <section className="w-[100%] lg:w-[50%] h-[50%] lg:h-[100%] flex justify-center items-center text-[.9rem] lg:text-[1rem]">
        <p>
          کلیه حقوق این سایت متعلق به کارتا می باشد. باز نویسی کامل توسط رضا
          اجاقی
        </p>
      </section>
      <section className="w-[100%] lg:w-[50%] h-[50%] lg:h-[100%] flex justify-center lg:justify-end text-[1.5rem] items-center gap-10 px-10">
        <i className="bi bi-telephone-fill" title="09121594246"></i>
        <Link href="https://www.instagram.com/reza-ojaghi-dro">
          <i className="bi bi-instagram"></i>
        </Link>
        <Link href="https://www.linkedin.com/in/reza-ojaghi-428748280/">
          <i className="bi bi-linkedin"></i>
        </Link>
        <Link href="https://github.com/REZA-OJAGHI-DRO">
          <i className="bi bi-github"></i>
        </Link>
      </section>
    </footer>
  );
}
